import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { ConvexClientProvider } from "@/lib/ConvexClientProvider";
import Header from "@/ui/header";
import { NavProvider } from "@/hooks/useNavOpen";
import NavGroup from "@/ui/navgroup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Denta Clinic Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <div className="flex justify-center items-center min-w-full  ">
            <main className="flex w-full h-full">
              <NavProvider>
                <NavGroup />
              </NavProvider>

              <div className="h-full w-full flex flex-col ">
                <Header type="Peripherals" />
                <article className=" font-Manrope mx-auto max-w-screen-xl px-4  md:flex md:flex-row  w-full h-[calc(100vh-60px)] ">
                  {children}
                </article>
              </div>
            </main>
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
