import type { Metadata } from "next";
import "../globals.css";
import { ConvexClientProvider } from "@/lib/ConvexClientProvider";
import { NavProvider } from "@/hooks/useNavOpen";
import NavGroup from "@/ui/navgroup";
import RootLayout from "../dashboard/layout";

export const metadata: Metadata = {
  title: "Denta Clinic Management System",
  description: "Generated by create next app",
};

export default function DesignLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayout>{children}</RootLayout>;
}
