import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { ConvexClientProvider } from "@/lib/ConvexClientProvider";
import { Providers } from "@/lib/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design System of Denta Clinic Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={
          inter.className +
          ` bg-lightbg text-black dark:bg-darkbg dark:text-white`
        }
      >
        <ConvexClientProvider>
          <Providers>{children}</Providers>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
