import type { Metadata } from "next";
import "../globals.css";
import { ConvexClientProvider } from "@/lib/ConvexClientProvider";
import { NavProvider } from "@/hooks/useNavOpen";
import NavGroup from "@/ui/navgroup";

export const metadata: Metadata = {
  title: "Denta Clinic Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <div className="flex justify-center items-center min-w-full  ">
            <main className="flex w-full h-full">
              <NavProvider>
                <NavGroup />
              </NavProvider>
              {children}
            </main>
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
