import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { ConvexClientProvider } from "@/lib/ConvexClientProvider";
import Header from "@/ui/header";
import { NavProvider } from "@/hooks/useNavOpen";
import NavGroup from "@/ui/navgroup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Denta Clinic Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full w-full flex flex-col ">
      <Header type="Stocks" />
      <article className=" font-Manrope mx-auto max-w-screen-xl px-4  md:flex md:flex-row  w-full h-[calc(100vh-60px)] ">
        {children}
      </article>
    </div>
  );
}
